AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An API to return one gig when you give it the gig slug
Resources:
  getOneGig:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handler.handler
      Runtime: nodejs6.10
      Policies: AWSLambdaDynamoDBExecutionRole
      # MemorySize: 128
      # Timeout: 3
      Events:
        Endpoint:
          Type: Api
          Properties:
            Path: /gig/{slug}
            Method: get

Outputs:
  endpoint:
    Description: The API Gateway endpoint for getting your gig
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com'
